package link.yggdrasil.yggstack.android.ui.theme

import androidx.compose.ui.graphics.Color

// Full Material 3 tonal-spot palette generated from the brand green seed
// (#006C4C) with @material/material-color-utilities — the same engine behind
// Material Theme Builder. Defining every role keeps the whole app (tonal
// buttons, dialogs, chips, outlines, surfaces) brand-tinted instead of
// falling back to the stock purple baseline.

// Light scheme
val md_theme_light_primary = Color(0xFF1F6A4E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA8F2CE)
val md_theme_light_onPrimaryContainer = Color(0xFF005138)
val md_theme_light_secondary = Color(0xFF4D6357)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCFE9D9)
val md_theme_light_onSecondaryContainer = Color(0xFF354B40)
val md_theme_light_tertiary = Color(0xFF3D6373)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC1E8FB)
val md_theme_light_onTertiaryContainer = Color(0xFF244C5B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF5FBF5)
val md_theme_light_onBackground = Color(0xFF171D1A)
val md_theme_light_surface = Color(0xFFF5FBF5)
val md_theme_light_onSurface = Color(0xFF171D1A)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DD)
val md_theme_light_onSurfaceVariant = Color(0xFF404943)
val md_theme_light_outline = Color(0xFF707973)
val md_theme_light_outlineVariant = Color(0xFFBFC9C2)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF2C322E)
val md_theme_light_inverseOnSurface = Color(0xFFEDF2EC)
val md_theme_light_inversePrimary = Color(0xFF8DD5B3)
val md_theme_light_surfaceDim = Color(0xFFD6DBD6)
val md_theme_light_surfaceBright = Color(0xFFF5FBF5)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFEFF5EF)
val md_theme_light_surfaceContainer = Color(0xFFEAEFEA)
val md_theme_light_surfaceContainerHigh = Color(0xFFE4EAE4)
val md_theme_light_surfaceContainerHighest = Color(0xFFDEE4DE)

// Dark scheme
val md_theme_dark_primary = Color(0xFF8DD5B3)
val md_theme_dark_onPrimary = Color(0xFF003826)
val md_theme_dark_primaryContainer = Color(0xFF005138)
val md_theme_dark_onPrimaryContainer = Color(0xFFA8F2CE)
val md_theme_dark_secondary = Color(0xFFB3CCBE)
val md_theme_dark_onSecondary = Color(0xFF1F352A)
val md_theme_dark_secondaryContainer = Color(0xFF354B40)
val md_theme_dark_onSecondaryContainer = Color(0xFFCFE9D9)
val md_theme_dark_tertiary = Color(0xFFA5CCDF)
val md_theme_dark_onTertiary = Color(0xFF073543)
val md_theme_dark_tertiaryContainer = Color(0xFF244C5B)
val md_theme_dark_onTertiaryContainer = Color(0xFFC1E8FB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F1512)
val md_theme_dark_onBackground = Color(0xFFDEE4DE)
val md_theme_dark_surface = Color(0xFF0F1512)
val md_theme_dark_onSurface = Color(0xFFDEE4DE)
val md_theme_dark_surfaceVariant = Color(0xFF404943)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C2)
val md_theme_dark_outline = Color(0xFF8A938C)
val md_theme_dark_outlineVariant = Color(0xFF404943)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFDEE4DE)
val md_theme_dark_inverseOnSurface = Color(0xFF2C322E)
val md_theme_dark_inversePrimary = Color(0xFF1F6A4E)
val md_theme_dark_surfaceDim = Color(0xFF0F1512)
val md_theme_dark_surfaceBright = Color(0xFF353B37)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0A0F0C)
val md_theme_dark_surfaceContainerLow = Color(0xFF171D1A)
val md_theme_dark_surfaceContainer = Color(0xFF1B211E)
val md_theme_dark_surfaceContainerHigh = Color(0xFF252B28)
val md_theme_dark_surfaceContainerHighest = Color(0xFF303632)
